platform:
  - x64

image: Visual Studio 2017

clone_depth: 1

environment:
  global:
    CYG_ROOT: C:\cygwin64
    CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    CYG_CACHE: C:/cygwin/var/cache/setup
  matrix:
    - OCAML_VERSION: 4.07.1
      PORT: mingw
    - OCAML_VERSION: 4.07.1
      PORT: mingw64
    - OCAML_VERSION: 4.07.1
      PORT: msvc
    - OCAML_VERSION: 4.07.1
      PORT: msvc64

cache:
  - C:\OCaml

install:
  - call "%APPVEYOR_BUILD_FOLDER%\appveyor.cmd"

build_script:
  - dune build
  - dune build test/cbclp.exe

test_script:
  - dune build @settests --auto-promote || ver>nul
  - dune runtest

# Uncomment this to enable Remote Desktop on the build worker at the end of the
# build. The worker is available for the remainder of the allocated hour.
#on_finish:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
